name: Build Android TV APK (armeabi-v7a)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # 安装 Rust
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv7-linux-androideabi

      # 安装 Android SDK + NDK
      - name: Install Android SDK and NDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          ndk: 25.2.9519653

      # 安装 cargo-apk (打包APK) 和 cargo-ndk
      - name: Install cargo-apk and cargo-ndk
        run: |
          cargo install cargo-ndk
          cargo install cargo-apk

      # 编译 ARMv7a APK
      - name: Build APK
        run: |
          cargo apk build --release --target=armv7-linux-androideabi

      # 上传 APK 产物
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OrionTV-armv7a
          path: target/debug/apk/*.apk
