name: Build OrionTV ARMv7

on:
  workflow_dispatch:   # 手动触发
  push:
    branches: [ main ] # 也可以改成你实际开发的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf pkg-config

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: armv7-unknown-linux-gnueabihf

      - name: Build for ARMv7
        run: |
          mkdir -p .cargo
          echo '[target.armv7-unknown-linux-gnueabihf]' >> .cargo/config.toml
          echo 'linker = "arm-linux-gnueabihf-gcc"' >> .cargo/config.toml
          cargo build --release --target=armv7-unknown-linux-gnueabihf

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: oriontv-armv7
          path: target/armv7-unknown-linux-gnueabihf/release/oriontv
