name: Build OrionTV Android TV (ARMv7a)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-android-tv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install dependencies
        run: yarn

      # 使用 expo prebuild 替代 prebuild-tv
      - name: Prebuild Android project
        run: npx expo prebuild --platform android

      - name: Build Android APK (ARMv7a)
        run: |
          cd android
          ./gradlew assembleRelease -PabiFilters=armeabi-v7a

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OrionTV-AndroidTV-ARMv7
          path: android/app/build/outputs/apk/release/app-release.apk
